// 成都周边游目的地数据
// 原点：成都站（0km）· 数据来源：官网+百度百科+XHS+大众点评
const DESTINATIONS_CD = [
  {
    id: 1300, name: "宽窄巷子", subtitle: "三条老巷·成都慢生活名片",
    distance: 3, distanceText: "3km",
    duration: ["半日游"], transport: ["地铁 M2 4 号线", "公交"],
    howToGet: "距市区约 3km；推荐搭乘地铁 M2 4 号线，到站后步行 5-10 分钟可达；可乘公交至目的地站点下车。",
    themes: ["古街", "美食", "文艺"],
    budget: "200以下", budgetText: "免费（人均 ¥80 小吃）",
    rating: 4.3,
    gradient: "linear-gradient(135deg, #8B4513 0%, #DAA520 100%)",
    whereToEat: "龙抄手 / 三大炮 / 钟水饺",
    whereToStay: "人民公园附近民宿",
    bestSeason: "春秋",
    tips: "1. 免费开放\n2. 宽巷子老宅子·窄巷子酒吧·井巷子小吃\n3. 避开周末下午人流高峰",
    highlight: "清代满城遗址·盖碗茶+糖油果子",
    tags: ["老巷", "盖碗茶", "川味", "网红", "成都地标"],
    imageQuery: "Chengdu Kuanzhai Alley traditional street"
  },
  {
    id: 1301, name: "大熊猫繁育研究基地", subtitle: "全球最大的熊猫人工繁育中心",
    distance: 10, distanceText: "10km",
    duration: ["半日游"], transport: ["地铁 M3", "公交"],
    howToGet: "距市区约 10km；推荐搭乘地铁 M3，到站后步行 5-10 分钟可达；可乘公交至目的地站点下车。",
    themes: ["动物", "亲子", "自然"],
    budget: "200-500", budgetText: "门票 ¥55",
    rating: 4.7,
    gradient: "linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)",
    whereToEat: "基地内熊猫主题餐厅 / 月子中心餐车",
    whereToStay: "熊猫大道沿线酒店",
    bestSeason: "春秋（上午 9-11 点熊猫最活跃）",
    tips: "1. 门票 ¥55·学生半价\n2. 必到月亮产房看新生幼崽\n3. 清晨 7:30 开门最佳",
    highlight: "130+ 大熊猫·'花花' 顶流明星",
    tags: ["熊猫", "花花", "亲子", "拍照", "国宝"],
    imageQuery: "Chengdu Panda Research Base giant pandas"
  },
  {
    id: 1302, name: "锦里古街", subtitle: "西蜀第一街·武侯祠旁",
    distance: 4, distanceText: "4km",
    duration: ["半日游"], transport: ["地铁 M3", "公交"],
    howToGet: "距市区约 4km；推荐搭乘地铁 M3，到站后步行 5-10 分钟可达；可乘公交至目的地站点下车。",
    themes: ["古街", "美食", "夜景"],
    budget: "200以下", budgetText: "免费（人均 ¥60 小吃）",
    rating: 4.4,
    gradient: "linear-gradient(135deg, #f7971e 0%, #ffd200 100%)",
    whereToEat: "三大炮 / 张飞牛肉 / 锦里酸辣粉",
    whereToStay: "武侯祠周边客栈",
    bestSeason: "四季，夜景最美",
    tips: "1. 免费\n2. 与武侯祠联票 ¥50\n3. 晚上 7 点后灯光秀",
    highlight: "三国文化主题·灯笼夜市",
    tags: ["三国", "灯笼", "小吃", "夜市", "武侯祠"],
    imageQuery: "Chengdu Jinli Ancient Street night lanterns"
  },
  {
    id: 1303, name: "都江堰", subtitle: "2250 年前李冰治水·世界遗产",
    distance: 56, distanceText: "56km",
    duration: ["一日往返"], transport: ["地铁 M4 接 都江堰快铁", "自驾"],
    howToGet: "距市区约 56km；推荐搭乘地铁 M4 接 都江堰快铁，到站后步行 5-10 分钟可达；自驾导航至目的地停车场（节假日建议早到）。",
    themes: ["历史", "自然", "世界遗产"],
    budget: "200-500", budgetText: "门票 ¥80",
    rating: 4.6,
    gradient: "linear-gradient(135deg, #5DADE2 0%, #1F618D 100%)",
    whereToEat: "灌县老街冷串串 / 尤兔头",
    whereToStay: "青城山脚下农家院",
    bestSeason: "春秋",
    tips: "1. 门票 ¥80\n2. 建议从南桥进伏龙观方向\n3. 可联游青城山",
    highlight: "鱼嘴·飞沙堰·宝瓶口 三大工程",
    tags: ["世界遗产", "水利", "都江堰", "李冰", "古代工程"],
    imageQuery: "Dujiangyan ancient irrigation system Sichuan"
  },
  {
    id: 1304, name: "青城山", subtitle: "道教四大名山·张天师道场",
    distance: 65, distanceText: "65km",
    duration: ["一日往返", "两日一夜"], transport: ["都江堰快铁+青城山支线", "自驾"],
    howToGet: "距市区约 65km；通过 都江堰快铁+青城山支线 抵达；自驾导航至目的地停车场（节假日建议早到）。",
    themes: ["爬山", "宗教", "自然"],
    budget: "200-500", budgetText: "门票 ¥90+索道 ¥60",
    rating: 4.5,
    gradient: "linear-gradient(135deg, #2E7D32 0%, #66BB6A 100%)",
    whereToEat: "青城四绝（老腊肉/白果炖鸡/洞天乳酒/道家泡菜）",
    whereToStay: "青城山上清宫周边客栈",
    bestSeason: "春夏最佳",
    tips: "1. 前山门票 ¥90·后山 ¥20\n2. 前山有名但后山更美\n3. 道教古寺可体验打坐",
    highlight: "张陵开道·青城天下幽",
    tags: ["道教", "世界遗产", "名山", "太极", "青城"],
    imageQuery: "Qingcheng Mountain Taoist temple Chengdu"
  },
  {
    id: 1305, name: "武侯祠", subtitle: "中国唯一君臣合祀的祠庙",
    distance: 4, distanceText: "4km",
    duration: ["半日游"], transport: ["地铁 M3", "公交"],
    howToGet: "距市区约 4km；推荐搭乘地铁 M3，到站后步行 5-10 分钟可达；可乘公交至目的地站点下车。",
    themes: ["历史", "博物馆", "三国"],
    budget: "200以下", budgetText: "门票 ¥50",
    rating: 4.4,
    gradient: "linear-gradient(135deg, #8B4513 0%, #A0522D 100%)",
    whereToEat: "锦里（紧邻）/ 陈麻婆豆腐",
    whereToStay: "武侯区酒店",
    bestSeason: "四季",
    tips: "1. 门票 ¥50\n2. 与锦里联游\n3. 诸葛亮殿必看",
    highlight: "刘备墓·诸葛亮祠·蜀汉文化",
    tags: ["三国", "蜀汉", "诸葛亮", "国保", "历史"],
    imageQuery: "Wuhou Shrine Chengdu Three Kingdoms"
  },
  {
    id: 1306, name: "峨眉山", subtitle: "普贤道场·四大佛教名山之一",
    distance: 160, distanceText: "160km",
    duration: ["两日一夜"], transport: ["高铁 1h+大巴", "自驾"],
    howToGet: "距市区约 160km；从就近高铁站/火车站出发，站外打车或接驳公交；自驾导航至目的地停车场（节假日建议早到）。",
    themes: ["爬山", "宗教", "日出"],
    budget: "500-1000", budgetText: "门票 ¥185+索道 ¥120+住宿",
    rating: 4.8,
    gradient: "linear-gradient(135deg, #37474F 0%, #78909C 100%)",
    whereToEat: "金顶素斋 / 灵秀温泉度假酒店",
    whereToStay: "金顶酒店（看日出）· 雷洞坪",
    bestSeason: "4-10月",
    tips: "1. 门票 ¥185（旺季）\n2. 金顶日出必看·需提前夜住\n3. 猴子多·背包别露吃的",
    highlight: "金顶日出·云海佛光·普贤菩萨",
    tags: ["佛教", "金顶", "日出", "峨眉山", "世界遗产"],
    imageQuery: "Emei Mountain Golden Summit sunrise Sichuan"
  },
  {
    id: 1307, name: "乐山大佛", subtitle: "世界最大石刻佛像·71m 高",
    distance: 155, distanceText: "155km",
    duration: ["一日往返"], transport: ["高铁+公交", "自驾"],
    howToGet: "距市区约 155km；可乘高铁+公交至目的地站点下车；自驾导航至目的地停车场（节假日建议早到）。",
    themes: ["历史", "佛教", "世界遗产"],
    budget: "200-500", budgetText: "门票 ¥80+游船 ¥70",
    rating: 4.6,
    gradient: "linear-gradient(135deg, #C62828 0%, #E57373 100%)",
    whereToEat: "跷脚牛肉 / 麻辣烫",
    whereToStay: "乐山中心酒店",
    bestSeason: "4-10月",
    tips: "1. 门票 ¥80\n2. 可步道爬近看或坐船远观\n3. 建议与峨眉山联游",
    highlight: "唐代凌云寺·三江汇流处",
    tags: ["大佛", "唐代", "世界遗产", "佛教", "乐山"],
    imageQuery: "Leshan Giant Buddha Sichuan"
  },
  {
    id: 1308, name: "西岭雪山", subtitle: "成都人的滑雪圣地",
    distance: 95, distanceText: "95km",
    duration: ["两日一夜"], transport: ["自驾", "大巴"],
    howToGet: "距市区约 95km；自驾导航至目的地停车场（节假日建议早到）；通过 大巴 抵达。",
    themes: ["爬山", "滑雪", "自然"],
    budget: "500-1000", budgetText: "门票 ¥130+索道 ¥120",
    rating: 4.5,
    gradient: "linear-gradient(135deg, #42A5F5 0%, #90CAF9 100%)",
    whereToEat: "雪山高山农家",
    whereToStay: "山顶雪山酒店",
    bestSeason: "12-3月（滑雪）/ 6-8月（避暑）",
    tips: "1. 冬季必带防寒装备\n2. 日月坪看雪最美\n3. 西岭雪山不等于西岭镇（县城）",
    highlight: "阴阳界·日月坪日出",
    tags: ["滑雪", "雪山", "避暑", "杜甫", "雪峰"],
    imageQuery: "Xiling Snow Mountain ski resort Sichuan"
  },
  {
    id: 1309, name: "杜甫草堂", subtitle: "诗圣杜甫在成都的旧居",
    distance: 5, distanceText: "5km",
    duration: ["半日游"], transport: ["公交", "地铁 M4"],
    howToGet: "距市区约 5km；可乘公交至目的地站点下车；推荐搭乘地铁 M4，到站后步行 5-10 分钟可达。",
    themes: ["历史", "文学", "博物馆"],
    budget: "200以下", budgetText: "门票 ¥50",
    rating: 4.5,
    gradient: "linear-gradient(135deg, #558B2F 0%, #9CCC65 100%)",
    whereToEat: "草堂附近小店",
    whereToStay: "青羊区酒店",
    bestSeason: "四季",
    tips: "1. 门票 ¥50\n2. 诗史堂看杜甫年谱\n3. 浣花溪公园紧邻",
    highlight: "杜甫'茅屋为秋风所破歌'原址",
    tags: ["杜甫", "诗史", "唐代", "文学", "国保"],
    imageQuery: "Du Fu Thatched Cottage Chengdu"
  },
  {
    id: 1310, name: "春熙路", subtitle: "成都最繁华商圈·IFS 爬墙熊猫",
    distance: 3, distanceText: "3km",
    duration: ["半日游"], transport: ["地铁 M2 M3"],
    howToGet: "距市区约 3km；推荐搭乘地铁 M2 M3，到站后步行 5-10 分钟可达。",
    themes: ["购物", "美食", "打卡"],
    budget: "200-500", budgetText: "人均 ¥150",
    rating: 4.4,
    gradient: "linear-gradient(135deg, #E91E63 0%, #FF9800 100%)",
    whereToEat: "蜀大侠火锅 / 大妙火锅 / 张唐老妈兔头",
    whereToStay: "春熙路 IFS / 太古里",
    bestSeason: "四季",
    tips: "1. 免费逛\n2. IFS 爬墙熊猫必拍\n3. 太古里周末人山人海",
    highlight: "IFS 爬墙熊猫·太古里·成都潮流中心",
    tags: ["商圈", "火锅", "潮流", "太古里", "成都打卡"],
    imageQuery: "Chengdu Taikooli IFS wall panda shopping"
  },
  {
    id: 1311, name: "人民公园", subtitle: "成都人喝茶打麻将的真·日常",
    distance: 3, distanceText: "3km",
    duration: ["半日游"], transport: ["地铁 M2"],
    howToGet: "距市区约 3km；推荐搭乘地铁 M2，到站后步行 5-10 分钟可达。",
    themes: ["休闲", "茶文化", "市井"],
    budget: "200以下", budgetText: "人均 ¥30（茶+瓜子）",
    rating: 4.5,
    gradient: "linear-gradient(135deg, #8D6E63 0%, #BCAAA4 100%)",
    whereToEat: "鹤鸣茶社（园内）· 周边钟水饺",
    whereToStay: "人民公园周边民宿",
    bestSeason: "四季，春秋最舒服",
    tips: "1. 免费\n2. 鹤鸣茶社 ¥10-30 一盏\n3. 采耳 ¥50 地道体验",
    highlight: "鹤鸣茶社·保路纪念碑·相亲角",
    tags: ["喝茶", "采耳", "市井", "老成都", "相亲角"],
    imageQuery: "Chengdu Peoples Park Heming Teahouse"
  }
];
if (typeof window !== 'undefined') window.DESTINATIONS_CD = DESTINATIONS_CD;
if (typeof module !== 'undefined' && module.exports) module.exports = DESTINATIONS_CD;
