// ========== Unique Stamp Designs for Each Destination ==========
// AI-generated stamp images where available, fallback to SVG

// AI-generated stamp image mapping (destination name → stamp image path)
const STAMP_IMAGES = {
  "古北水镇": "assets/stamps/stamp-1.webp",
  "雾灵山": "assets/stamps/stamp-10.webp",
  "延庆龙庆峡冰灯节": "assets/stamps/stamp-100.webp",
  "密云司马台长城": "assets/stamps/stamp-101.webp",
  "恋乡太行水镇": "assets/stamps/stamp-102.webp",
  "张北草原天路": "assets/stamps/stamp-11.webp",
  "阿那亚": "assets/stamps/stamp-12.webp",
  "黄花城水长城": "assets/stamps/stamp-13.webp",
  "青龙峡": "assets/stamps/stamp-14.webp",
  "神堂峪": "assets/stamps/stamp-15.webp",
  "喇叭沟原始森林": "assets/stamps/stamp-16.webp",
  "雁栖湖": "assets/stamps/stamp-17.webp",
  "潭柘寺": "assets/stamps/stamp-18.webp",
  "野三坡": "assets/stamps/stamp-19.webp",
  "延庆百里画廊": "assets/stamps/stamp-2.webp",
  "白石山": "assets/stamps/stamp-20.webp",
  "白河峡谷": "assets/stamps/stamp-200.webp",
  "幽谷神潭": "assets/stamps/stamp-201.webp",
  "云蒙山": "assets/stamps/stamp-202.webp",
  "海坨山": "assets/stamps/stamp-203.webp",
  "百花山": "assets/stamps/stamp-204.webp",
  "官厅水库": "assets/stamps/stamp-205.webp",
  "桃源仙谷": "assets/stamps/stamp-206.webp",
  "云蒙峡": "assets/stamps/stamp-207.webp",
  "798艺术区": "assets/stamps/stamp-208.webp",
  "首钢园": "assets/stamps/stamp-209.webp",
  "北戴河": "assets/stamps/stamp-21.webp",
  "前门大栅栏": "assets/stamps/stamp-210.webp",
  "鸟巢水立方": "assets/stamps/stamp-211.webp",
  "延庆野鸭湖湿地": "assets/stamps/stamp-212.webp",
  "汉石桥湿地": "assets/stamps/stamp-213.webp",
  "翠湖湿地公园": "assets/stamps/stamp-214.webp",
  "灵水举人村": "assets/stamps/stamp-215.webp",
  "水峪村": "assets/stamps/stamp-216.webp",
  "琉璃渠村": "assets/stamps/stamp-217.webp",
  "军都山滑雪场": "assets/stamps/stamp-218.webp",
  "怀北滑雪场": "assets/stamps/stamp-219.webp",
  "凤凰岭": "assets/stamps/stamp-22.webp",
  "九华山庄温泉": "assets/stamps/stamp-220.webp",
  "春晖园温泉": "assets/stamps/stamp-221.webp",
  "天津古文化街": "assets/stamps/stamp-222.webp",
  "蓟州独乐寺": "assets/stamps/stamp-223.webp",
  "房山云居寺": "assets/stamps/stamp-224.webp",
  "白瀑寺": "assets/stamps/stamp-225.webp",
  "龙门涧": "assets/stamps/stamp-226.webp",
  "居庸关花海列车": "assets/stamps/stamp-227.webp",
  "黄草梁": "assets/stamps/stamp-228.webp",
  "东灵山": "assets/stamps/stamp-229.webp",
  "坝上草原": "assets/stamps/stamp-23.webp",
  "密云桃园仙谷": "assets/stamps/stamp-230.webp",
  "怀柔水库": "assets/stamps/stamp-231.webp",
  "密云黑山寺": "assets/stamps/stamp-232.webp",
  "遥桥峪村": "assets/stamps/stamp-233.webp",
  "北京野生动物园": "assets/stamps/stamp-234.webp",
  "世界公园": "assets/stamps/stamp-235.webp",
  "中国园林博物馆": "assets/stamps/stamp-236.webp",
  "北京天文馆": "assets/stamps/stamp-237.webp",
  "故宫角楼咖啡": "assets/stamps/stamp-238.webp",
  "蔡家洼玫瑰园": "assets/stamps/stamp-239.webp",
  "大觉寺": "assets/stamps/stamp-24.webp",
  "北京植物园牡丹节": "assets/stamps/stamp-240.webp",
  "白草畔": "assets/stamps/stamp-241.webp",
  "北京欢乐水魔方": "assets/stamps/stamp-242.webp",
  "北京奥林匹克塔": "assets/stamps/stamp-243.webp",
  "怀来葡萄酒庄": "assets/stamps/stamp-244.webp",
  "平谷大峡谷": "assets/stamps/stamp-245.webp",
  "雁栖湖国际会都": "assets/stamps/stamp-246.webp",
  "平谷老泰山": "assets/stamps/stamp-247.webp",
  "昌平十三陵水库": "assets/stamps/stamp-248.webp",
  "妙峰山": "assets/stamps/stamp-25.webp",
  "周口店遗址": "assets/stamps/stamp-26.webp",
  "古崖居": "assets/stamps/stamp-27.webp",
  "龙庆峡": "assets/stamps/stamp-28.webp",
  "百望山": "assets/stamps/stamp-29.webp",
  "密云水库": "assets/stamps/stamp-3.webp",
  "崇礼": "assets/stamps/stamp-30.webp",
  "房山十字寺": "assets/stamps/stamp-31.webp",
  "灵山": "assets/stamps/stamp-32.webp",
  "爨底下村": "assets/stamps/stamp-33.webp",
  "承德避暑山庄": "assets/stamps/stamp-34.webp",
  "玉渡山": "assets/stamps/stamp-35.webp",
  "小汤山温泉": "assets/stamps/stamp-36.webp",
  "蔚县暖泉古镇": "assets/stamps/stamp-37.webp",
  "戒台寺": "assets/stamps/stamp-38.webp",
  "奥林匹克森林公园": "assets/stamps/stamp-39.webp",
  "慕田峪长城": "assets/stamps/stamp-4.webp",
  "香山公园": "assets/stamps/stamp-40.webp",
  "国家植物园": "assets/stamps/stamp-41.webp",
  "十三陵": "assets/stamps/stamp-42.webp",
  "居庸关长城": "assets/stamps/stamp-43.webp",
  "房山石花洞": "assets/stamps/stamp-45.webp",
  "天津五大道": "assets/stamps/stamp-46.webp",
  "天津之眼摩天轮": "assets/stamps/stamp-47.webp",
  "蓟州盘山": "assets/stamps/stamp-48.webp",
  "保定直隶总督署": "assets/stamps/stamp-49.webp",
  "金海湖": "assets/stamps/stamp-5.webp",
  "清西陵": "assets/stamps/stamp-50.webp",
  "易水湖": "assets/stamps/stamp-51.webp",
  "张裕爱斐堡酒庄": "assets/stamps/stamp-52.webp",
  "渔阳滑雪场": "assets/stamps/stamp-53.webp",
  "延庆世园公园": "assets/stamps/stamp-54.webp",
  "平谷桃花海": "assets/stamps/stamp-55.webp",
  "门头沟双龙峡": "assets/stamps/stamp-56.webp",
  "京西古道": "assets/stamps/stamp-57.webp",
  "昌平碓臼峪": "assets/stamps/stamp-58.webp",
  "大兴野生动物园": "assets/stamps/stamp-59.webp",
  "十渡风景区": "assets/stamps/stamp-6.webp",
  "通州大运河森林公园": "assets/stamps/stamp-60.webp",
  "顺义奥林匹克水上公园": "assets/stamps/stamp-61.webp",
  "焦庄户地道战遗址": "assets/stamps/stamp-62.webp",
  "秦皇岛山海关": "assets/stamps/stamp-63.webp",
  "张家口暖泉古镇": "assets/stamps/stamp-64.webp",
  "丫髻山": "assets/stamps/stamp-65.webp",
  "南海子公园": "assets/stamps/stamp-66.webp",
  "箭扣长城": "assets/stamps/stamp-67.webp",
  "怀柔虹鳟鱼一条沟": "assets/stamps/stamp-68.webp",
  "松山自然保护区": "assets/stamps/stamp-69.webp",
  "蟒山国家森林公园": "assets/stamps/stamp-7.webp",
  "白洋淀": "assets/stamps/stamp-70.webp",
  "中国科学技术馆": "assets/stamps/stamp-71.webp",
  "房山世界地质公园": "assets/stamps/stamp-72.webp",
  "颐和园昆明湖": "assets/stamps/stamp-73.webp",
  "八达岭野生动物园": "assets/stamps/stamp-74.webp",
  "怀柔影视城": "assets/stamps/stamp-75.webp",
  "延庆万亩杏花": "assets/stamps/stamp-76.webp",
  "银山塔林": "assets/stamps/stamp-77.webp",
  "涞水野三坡百里峡": "assets/stamps/stamp-78.webp",
  "崇礼万龙滑雪场": "assets/stamps/stamp-79.webp",
  "南山滑雪场": "assets/stamps/stamp-8.webp",
  "密云古北口": "assets/stamps/stamp-80.webp",
  "圣莲山": "assets/stamps/stamp-81.webp",
  "上方山国家森林公园": "assets/stamps/stamp-82.webp",
  "雄安新区容东片区": "assets/stamps/stamp-83.webp",
  "石景山游乐园": "assets/stamps/stamp-84.webp",
  "永定河生态走廊": "assets/stamps/stamp-85.webp",
  "古北水镇附近司马台水库": "assets/stamps/stamp-86.webp",
  "北京植物园（原北植）": "assets/stamps/stamp-87.webp",
  "张家口大境门": "assets/stamps/stamp-88.webp",
  "北京欢乐谷": "assets/stamps/stamp-89.webp",
  "红螺寺": "assets/stamps/stamp-9.webp",
  "北京环球影城": "assets/stamps/stamp-90.webp",
  "坝上围场御道口": "assets/stamps/stamp-91.webp",
  "北戴河蔚蓝海岸": "assets/stamps/stamp-92.webp",
  "唐山南湖公园": "assets/stamps/stamp-93.webp",
  "灵山天池": "assets/stamps/stamp-94.webp",
  "黑龙潭": "assets/stamps/stamp-95.webp",
  "拒马河天然浴场": "assets/stamps/stamp-96.webp",
  "延庆硅化木地质公园": "assets/stamps/stamp-97.webp",
  "承德外八庙": "assets/stamps/stamp-98.webp",
  "北京明城墙遗址公园": "assets/stamps/stamp-99.webp",
  "故宫": "assets/stamps/stamp-330.webp",
  "天坛": "assets/stamps/stamp-331.webp",
  "北京动物园": "assets/stamps/stamp-332.webp",
  "北京海洋馆": "assets/stamps/stamp-333.webp",
  "烟袋斜街": "assets/stamps/stamp-334.webp",
  "五道营胡同": "assets/stamps/stamp-335.webp",
  "三里屯": "assets/stamps/stamp-336.webp",
  "中国美术馆": "assets/stamps/stamp-337.webp",
  "国家博物馆": "assets/stamps/stamp-338.webp",
  "景山公园": "assets/stamps/stamp-339.webp",
  "玉渊潭公园": "assets/stamps/stamp-340.webp",
  "紫竹院公园": "assets/stamps/stamp-341.webp",
  "陶然亭公园": "assets/stamps/stamp-342.webp",
  "朝阳公园": "assets/stamps/stamp-343.webp",
  "天津海河夜游": "assets/stamps/stamp-344.webp",
  "天津瓷房子": "assets/stamps/stamp-345.webp",
  "天津滨海图书馆": "assets/stamps/stamp-346.webp",
  "杨柳青古镇": "assets/stamps/stamp-347.webp",
  "天津航母主题公园": "assets/stamps/stamp-348.webp",
  "黄崖关长城": "assets/stamps/stamp-349.webp",
  "承德金山岭长城": "assets/stamps/stamp-350.webp",
  "秦皇岛老龙头": "assets/stamps/stamp-351.webp",
  "北戴河鸽子窝": "assets/stamps/stamp-352.webp",
  "乐亭月坨岛": "assets/stamps/stamp-353.webp",
  "唐山清东陵": "assets/stamps/stamp-354.webp",
  "张家口鸡鸣驿": "assets/stamps/stamp-355.webp",
  "廊坊天下第一城": "assets/stamps/stamp-356.webp",
  "石家庄西柏坡": "assets/stamps/stamp-357.webp",
  "石家庄抱犊寨": "assets/stamps/stamp-358.webp",
  "保定白洋淀温泉": "assets/stamps/stamp-359.webp",
  "淄博烧烤": "assets/stamps/stamp-360.webp",
  "潍坊风筝博物馆": "assets/stamps/stamp-361.webp",
  "临沂蒙山": "assets/stamps/stamp-362.webp",
  "枣庄台儿庄古城": "assets/stamps/stamp-363.webp",
  "东营黄河入海口": "assets/stamps/stamp-364.webp",
  "蓬莱八仙渡": "assets/stamps/stamp-365.webp",
  "栖霞牟氏庄园": "assets/stamps/stamp-366.webp",
  "泰安岱庙": "assets/stamps/stamp-367.webp",
  "济宁水泊梁山": "assets/stamps/stamp-368.webp",
  "太原晋祠": "assets/stamps/stamp-369.webp",
  "大同华严寺": "assets/stamps/stamp-370.webp",
  "乔家大院": "assets/stamps/stamp-371.webp",
  "王家大院": "assets/stamps/stamp-372.webp",
  "太行山大峡谷": "assets/stamps/stamp-373.webp",
  "晋城皇城相府": "assets/stamps/stamp-374.webp",
  "焦作云台山": "assets/stamps/stamp-375.webp",
  "开封清明上河园": "assets/stamps/stamp-376.webp",
  "沈阳故宫": "assets/stamps/stamp-377.webp",
  "大连金石滩": "assets/stamps/stamp-378.webp",
  "大连老虎滩": "assets/stamps/stamp-379.webp",
  "丹东鸭绿江": "assets/stamps/stamp-380.webp",
  "鞍山千山": "assets/stamps/stamp-381.webp",
  "本溪水洞": "assets/stamps/stamp-382.webp",
  "葫芦岛兴城古城": "assets/stamps/stamp-383.webp",
  "营口鲅鱼圈": "assets/stamps/stamp-384.webp",
  "邢台崆山白云洞": "assets/stamps/stamp-385.webp",
  "沧州吴桥杂技": "assets/stamps/stamp-386.webp",
  "衡水武强年画": "assets/stamps/stamp-387.webp",
  "承德磬锤峰": "assets/stamps/stamp-388.webp",
  "秦皇岛板厂峪长城": "assets/stamps/stamp-389.webp",
  "史家胡同博物馆": "assets/stamps/stamp-430.webp",
  "东交民巷使馆区": "assets/stamps/stamp-431.webp",
  "牛街清真寺": "assets/stamps/stamp-432.webp",
  "法源寺": "assets/stamps/stamp-433.webp",
  "白塔寺胡同": "assets/stamps/stamp-434.webp",
  "杨梅竹斜街": "assets/stamps/stamp-435.webp",
  "西什库教堂": "assets/stamps/stamp-436.webp",
  "智化寺": "assets/stamps/stamp-437.webp",
  "广化寺": "assets/stamps/stamp-438.webp",
  "报国寺文化市场": "assets/stamps/stamp-439.webp",
  "钟鼓楼广场": "assets/stamps/stamp-440.webp",
  "宣南文化博物馆": "assets/stamps/stamp-441.webp",
  "琉璃厂西街": "assets/stamps/stamp-442.webp",
  "大栅栏观音寺": "assets/stamps/stamp-443.webp",
  "京顺园": "assets/stamps/stamp-444.webp",
  "77文创园": "assets/stamps/stamp-445.webp",
  "郎园Station": "assets/stamps/stamp-446.webp",
  "模范书局·诗空间": "assets/stamps/stamp-447.webp",
  "角楼图书馆": "assets/stamps/stamp-448.webp",
  "PAGEONE北京坊": "assets/stamps/stamp-449.webp",
  "红砖美术馆": "assets/stamps/stamp-450.webp",
  "木木美术馆": "assets/stamps/stamp-451.webp",
  "尤伦斯当代艺术中心(UCCA)": "assets/stamps/stamp-452.webp",
  "松美术馆": "assets/stamps/stamp-453.webp",
  "中间美术馆": "assets/stamps/stamp-454.webp",
  "地坛公园银杏大道": "assets/stamps/stamp-455.webp",
  "柳荫公园": "assets/stamps/stamp-456.webp",
  "日坛公园": "assets/stamps/stamp-457.webp",
  "月坛公园": "assets/stamps/stamp-458.webp",
  "先农坛": "assets/stamps/stamp-459.webp",
  "团结湖公园": "assets/stamps/stamp-460.webp",
  "青年湖公园": "assets/stamps/stamp-461.webp",
  "人定湖公园": "assets/stamps/stamp-462.webp",
  "龙潭西湖": "assets/stamps/stamp-463.webp",
  "元大都城垣遗址公园": "assets/stamps/stamp-464.webp",
  "正阳门箭楼": "assets/stamps/stamp-465.webp",
  "德胜门箭楼": "assets/stamps/stamp-466.webp",
  "北京古观象台": "assets/stamps/stamp-467.webp",
  "五塔寺(真觉寺)": "assets/stamps/stamp-468.webp",
  "万寿寺(北京艺术博物馆)": "assets/stamps/stamp-469.webp",
  "大钟寺古钟博物馆": "assets/stamps/stamp-470.webp",
  "徐悲鸿纪念馆": "assets/stamps/stamp-471.webp",
  "梅兰芳纪念馆": "assets/stamps/stamp-472.webp",
  "老舍纪念馆": "assets/stamps/stamp-473.webp",
  "宋庆龄故居": "assets/stamps/stamp-474.webp",
  "护国寺小吃街": "assets/stamps/stamp-475.webp",
  "簋街": "assets/stamps/stamp-476.webp",
  "鬼市(潘家园天光墟)": "assets/stamps/stamp-477.webp",
  "花市清真寺旁牛羊肉胡同": "assets/stamps/stamp-478.webp",
  "天桥市井美食": "assets/stamps/stamp-479.webp",
  "雍和宫附近的五道营创意区": "assets/stamps/stamp-480.webp",
  "天宁寺塔": "assets/stamps/stamp-481.webp",
  "碧云寺金刚宝座塔": "assets/stamps/stamp-482.webp",
  "卧佛寺": "assets/stamps/stamp-483.webp",
  "妙应寺白塔": "assets/stamps/stamp-484.webp",
  "北海团城": "assets/stamps/stamp-485.webp",
  "什刹海银锭桥": "assets/stamps/stamp-486.webp",
  "后海小巷子": "assets/stamps/stamp-487.webp",
  "751D·PARK": "assets/stamps/stamp-488.webp",
  "恒通商务园": "assets/stamps/stamp-489.webp",
  "莱锦创意产业园": "assets/stamps/stamp-490.webp",
  "铜牛电影产业园": "assets/stamps/stamp-491.webp",
  "懋隆文化产业创意园": "assets/stamps/stamp-492.webp",
  "京棉二厂创意园": "assets/stamps/stamp-493.webp",
  "竞园艺术中心": "assets/stamps/stamp-494.webp",
  "二七厂1897科创城": "assets/stamps/stamp-495.webp",
  "百花深处胡同": "assets/stamps/stamp-496.webp",
  "八大胡同历史文化区": "assets/stamps/stamp-497.webp",
  "崇效寺遗址": "assets/stamps/stamp-498.webp",
  "报恩寺(南锣鼓巷旁)": "assets/stamps/stamp-499.webp",
  "金中都城墙遗址": "assets/stamps/stamp-500.webp",
  "万松老人塔": "assets/stamps/stamp-501.webp",
  "广福观": "assets/stamps/stamp-502.webp",
  "火神庙": "assets/stamps/stamp-503.webp",
  "中国邮政邮票博物馆": "assets/stamps/stamp-504.webp",
  "北京自来水博物馆": "assets/stamps/stamp-505.webp",
  "北京警察博物馆": "assets/stamps/stamp-506.webp",
  "中国电影博物馆": "assets/stamps/stamp-507.webp",
  "中国铁道博物馆": "assets/stamps/stamp-508.webp",
  "北京航空航天博物馆": "assets/stamps/stamp-509.webp",
  "首都粮食博物馆": "assets/stamps/stamp-510.webp",
  "北京印刷博物馆": "assets/stamps/stamp-511.webp",
  "玉渊潭樱花": "assets/stamps/stamp-512.webp",
  "紫竹院海棠花廊": "assets/stamps/stamp-513.webp",
  "海淀公园银杏": "assets/stamps/stamp-514.webp",
  "奥森北园彩叶林": "assets/stamps/stamp-515.webp",
  "北宫国家森林公园红叶": "assets/stamps/stamp-516.webp",
  "大运河森林公园秋色": "assets/stamps/stamp-517.webp",
  "通州运河夜景": "assets/stamps/stamp-518.webp",
  "温榆河公园": "assets/stamps/stamp-519.webp",
  "中央电视塔观景台": "assets/stamps/stamp-520.webp",
  "国贸三期80层": "assets/stamps/stamp-521.webp",
  "望京SOHO日落": "assets/stamps/stamp-522.webp",
  "银河SOHO建筑摄影": "assets/stamps/stamp-523.webp",
  "丽泽商务区SOHO": "assets/stamps/stamp-524.webp",
  "三里屯太古里": "assets/stamps/stamp-525.webp",
  "工体夜生活圈": "assets/stamps/stamp-526.webp",
  "鼓楼东大街酒吧": "assets/stamps/stamp-527.webp",
  "五道营深夜食堂": "assets/stamps/stamp-528.webp",
  "东四胡同深夜咖啡": "assets/stamps/stamp-529.webp",
  "朝内大街81号": "assets/stamps/stamp-530.webp",
  "北新桥锁龙井": "assets/stamps/stamp-531.webp",
  "西单小石虎胡同": "assets/stamps/stamp-532.webp",
  "虎坊桥湖广会馆": "assets/stamps/stamp-533.webp",
  "石虎胡同七号": "assets/stamps/stamp-534.webp",
  "礼王府": "assets/stamps/stamp-535.webp",
  "西安门大街鬼宅": "assets/stamps/stamp-536.webp",
  "菜市口刑场旧址": "assets/stamps/stamp-537.webp",
  "京张铁路青龙桥站": "assets/stamps/stamp-538.webp",
  "前门老火车站": "assets/stamps/stamp-539.webp",
  "北京饭店百年老楼": "assets/stamps/stamp-540.webp",
  "东单三条协和别墅群": "assets/stamps/stamp-541.webp",
  "京师大学堂旧址": "assets/stamps/stamp-542.webp",
  "段祺瑞执政府旧址": "assets/stamps/stamp-543.webp",
  "张自忠路原北平市政府": "assets/stamps/stamp-544.webp",
  "中南海邮局": "assets/stamps/stamp-545.webp",
  "北京地下城": "assets/stamps/stamp-546.webp",
  "前门地下街": "assets/stamps/stamp-547.webp",
  "正阳门城楼内部": "assets/stamps/stamp-548.webp",
  "钟楼内部": "assets/stamps/stamp-549.webp",
  "鼓楼二层击鼓表演": "assets/stamps/stamp-550.webp",
  "国子监辟雍": "assets/stamps/stamp-551.webp",
  "孔庙古柏触奸柏": "assets/stamps/stamp-552.webp",
  "鲁迅故居（阜成门）": "assets/stamps/stamp-553.webp",
  "齐白石旧居纪念馆": "assets/stamps/stamp-554.webp",
  "郭沫若故居": "assets/stamps/stamp-555.webp",
  "茅盾故居": "assets/stamps/stamp-556.webp",
  "曹禺故居": "assets/stamps/stamp-557.webp",
  "谭嗣同故居（浏阳会馆）": "assets/stamps/stamp-558.webp",
  "蔡锷故居（松坡图书馆）": "assets/stamps/stamp-559.webp",
  "李大钊故居": "assets/stamps/stamp-560.webp",
  "南锣鼓巷最后的大杂院": "assets/stamps/stamp-561.webp",
  "东四四条手工铁匠铺": "assets/stamps/stamp-562.webp",
  "前门打磨厂老字号": "assets/stamps/stamp-563.webp",
  "牛街最后的传统屠宰坊参观": "assets/stamps/stamp-564.webp",
  "天桥杂耍艺人": "assets/stamps/stamp-565.webp",
  "琉璃厂最后的手工宣纸作坊": "assets/stamps/stamp-566.webp",
  "东来顺涮肉总店": "assets/stamps/stamp-567.webp",
  "天坛相亲角": "assets/stamps/stamp-568.webp",
  "地坛书市": "assets/stamps/stamp-569.webp",
  "潘家园凌晨鬼市": "assets/stamps/stamp-570.webp",
  "报国寺古玩早市": "assets/stamps/stamp-571.webp",
  "天安门凌晨看升旗": "assets/stamps/stamp-572.webp",
  "景山公园日出俯瞰故宫": "assets/stamps/stamp-573.webp",
  "什刹海冬泳老人": "assets/stamps/stamp-574.webp",
  "三联韬奋书店（24小时）": "assets/stamps/stamp-575.webp",
  "凌晨4点的簋街": "assets/stamps/stamp-576.webp",
  "后海酒吧街凌晨散场": "assets/stamps/stamp-577.webp",
  "天桥德云社散场宵夜": "assets/stamps/stamp-578.webp",
  "北京站凌晨候车室众生相": "assets/stamps/stamp-579.webp",
  "景山崇祯自缢处": "assets/stamps/stamp-580.webp",
  "故宫珍妃井": "assets/stamps/stamp-581.webp",
  "故宫九龙壁修补秘密": "assets/stamps/stamp-582.webp",
  "北海五龙亭": "assets/stamps/stamp-583.webp",
  "颐和园铜牛": "assets/stamps/stamp-584.webp",
  "圆明园大水法遗址": "assets/stamps/stamp-585.webp",
  "雍正潜邸雍和宫": "assets/stamps/stamp-586.webp",
  "恭王府藏宝楼": "assets/stamps/stamp-587.webp",
  "同仁堂总店": "assets/stamps/stamp-588.webp",
  "全聚德前门店": "assets/stamps/stamp-589.webp",
  "瑞蚨祥绸缎庄": "assets/stamps/stamp-590.webp",
  "荣宝斋": "assets/stamps/stamp-591.webp",
  "内联升布鞋": "assets/stamps/stamp-592.webp",
  "张一元茶庄": "assets/stamps/stamp-593.webp",
  "吴裕泰茶庄": "assets/stamps/stamp-594.webp",
  "央视大裤衩": "assets/stamps/stamp-595.webp",
  "望京SOHO扎哈遗作": "assets/stamps/stamp-596.webp",
  "国家大剧院水下通道": "assets/stamps/stamp-597.webp",
  "鸟巢内部钢结构": "assets/stamps/stamp-598.webp",
  "中国尊顶层": "assets/stamps/stamp-599.webp",
  "银河SOHO探秘扎哈曲线": "assets/stamps/stamp-600.webp",
  "凤凰国际传媒中心": "assets/stamps/stamp-601.webp",
  "天子大酒店福禄寿": "assets/stamps/stamp-602.webp",
  "百花深处胡同探秘陈凯歌MV": "assets/stamps/stamp-603.webp",
  "帽儿胡同探秘婉容旧事": "assets/stamps/stamp-604.webp",
  "菊儿胡同吴良镛设计": "assets/stamps/stamp-605.webp",
  "砖塔胡同最古老": "assets/stamps/stamp-606.webp",
  "东堂子胡同蔡元培": "assets/stamps/stamp-607.webp",
  "西堂子胡同中国电影发源地": "assets/stamps/stamp-608.webp",
  "铁狮子胡同探秘段祺瑞府": "assets/stamps/stamp-609.webp",
  "棉花胡同蔡锷小凤仙传奇": "assets/stamps/stamp-610.webp",
  "中轴线永定门": "assets/stamps/stamp-611.webp",
  "中轴线钟鼓楼报时秘密": "assets/stamps/stamp-612.webp",
  "北京城几何中心": "assets/stamps/stamp-613.webp",
  "通州海拔最低点": "assets/stamps/stamp-614.webp",
  "钱市胡同最窄": "assets/stamps/stamp-615.webp",
  "一尺大街最短": "assets/stamps/stamp-616.webp",
  "天安门城楼内部探秘": "assets/stamps/stamp-617.webp",
  "故宫角楼雪景": "assets/stamps/stamp-618.webp",
  "颐和园十七孔桥金光穿洞": "assets/stamps/stamp-619.webp",
  "北海荷花映白塔": "assets/stamps/stamp-620.webp",
  "香山红叶隧道": "assets/stamps/stamp-621.webp",
  "玉渊潭冰雪嘉年华": "assets/stamps/stamp-622.webp",
  "卤煮火烧小肠陈": "assets/stamps/stamp-623.webp",
  "豆汁儿锦馨": "assets/stamps/stamp-624.webp",
  "炸酱面海碗居": "assets/stamps/stamp-625.webp",
  "涮羊肉南门涮肉": "assets/stamps/stamp-626.webp",
  "烤肉季烤肉宛": "assets/stamps/stamp-627.webp",
  "门钉肉饼": "assets/stamps/stamp-628.webp",
  "护国寺艾窝窝驴打滚": "assets/stamps/stamp-629.webp",
  "泰山": "assets/stamps/stamp-301.webp",
  "锦州笔架山": "assets/stamps/stamp-321.webp",
  "盘锦红海滩": "assets/stamps/stamp-322.webp",
  "开封": "assets/stamps/stamp-323.webp",
  "郑州少林寺": "assets/stamps/stamp-324.webp",
  "安阳殷墟": "assets/stamps/stamp-325.webp",
  "邢台大峡谷": "assets/stamps/stamp-326.webp",
  "赵州桥": "assets/stamps/stamp-327.webp",
  "唐山滦州古城": "assets/stamps/stamp-328.webp",
  "洛阳龙门石窟": "assets/stamps/stamp-329.webp",
  "颐和园": "assets/stamps/stamp-332.webp",
  "什刹海酒吧街": "assets/stamps/stamp-335.webp",
  "望京SOHO": "assets/stamps/stamp-339.webp",
  "北京天桥艺术中心": "assets/stamps/stamp-342.webp",
  "北京大学/清华大学参观": "assets/stamps/stamp-348.webp",
  "什刹海冰场": "assets/stamps/stamp-349.webp",
  "白洋淀荷花节": "assets/stamps/stamp-350.webp",
  "野三坡百里峡漂流": "assets/stamps/stamp-351.webp",
  "保定野三坡十渡漂流": "assets/stamps/stamp-363.webp",
  "张家口翠云山": "assets/stamps/stamp-366.webp",
  "唐山开滦矿山公园": "assets/stamps/stamp-369.webp",
  "天津小白楼": "assets/stamps/stamp-373.webp",
  "独流老醋博物馆": "assets/stamps/stamp-377.webp",
  "天津水上公园": "assets/stamps/stamp-378.webp",
  "天津自然博物馆": "assets/stamps/stamp-379.webp",
  "聊城光岳楼": "assets/stamps/stamp-384.webp",
  "菏泽牡丹园": "assets/stamps/stamp-385.webp",
  "长岛万鸟岛": "assets/stamps/stamp-388.webp",
  "荣成天鹅湖": "assets/stamps/stamp-389.webp",
  "沂蒙山银座天蒙": "assets/stamps/stamp-391.webp",
  "微山湖红荷湿地": "assets/stamps/stamp-392.webp",
  "青岛崂山太清宫": "assets/stamps/stamp-395.webp",
  "烟台金沙滩": "assets/stamps/stamp-396.webp",
  "威海赤山": "assets/stamps/stamp-397.webp",
  "日照万平口": "assets/stamps/stamp-398.webp",
  "青岛八大关秋景": "assets/stamps/stamp-399.webp",
  "云冈石窟夜游": "assets/stamps/stamp-402.webp",
  "绵山": "assets/stamps/stamp-405.webp",
  "壶口瀑布冬季冰瀑": "assets/stamps/stamp-406.webp",
  "运城盐湖": "assets/stamps/stamp-409.webp",
  "洛阳白马寺": "assets/stamps/stamp-410.webp",
  "洛阳老君山": "assets/stamps/stamp-411.webp",
  "新乡八里沟": "assets/stamps/stamp-414.webp",
  "林州红旗渠": "assets/stamps/stamp-415.webp",
  "安阳汤阴岳飞庙": "assets/stamps/stamp-416.webp",
  "盘锦红海滩落日": "assets/stamps/stamp-418.webp",
  "辽阳白塔": "assets/stamps/stamp-425.webp",
  "朝阳北票化石群": "assets/stamps/stamp-426.webp",
  "铁岭龙首山": "assets/stamps/stamp-428.webp",
  "锦州医巫闾山": "assets/stamps/stamp-429.webp",
  "北京SKP": "assets/stamps/stamp-650.webp",
  "合生汇": "assets/stamps/stamp-651.webp",
  "华熙LIVE·五棵松": "assets/stamps/stamp-652.webp",
  "西单更新场": "assets/stamps/stamp-653.webp",
  "THE BOX朝外": "assets/stamps/stamp-654.webp",
  "大悦春风里": "assets/stamps/stamp-655.webp",
  "湾里": "assets/stamps/stamp-656.webp",
  "北京太古坊": "assets/stamps/stamp-657.webp",
  "菖蒲河公园": "assets/stamps/stamp-658.webp",
  "镇罗营梨花谷": "assets/stamps/stamp-659.webp",
  "大梅沙海滨公园": "assets/stamps/stamp-sz-500.webp",
  "东部华侨城": "assets/stamps/stamp-sz-501.webp",
  "世界之窗": "assets/stamps/stamp-sz-502.webp",
  "深圳欢乐谷": "assets/stamps/stamp-sz-503.webp",
  "深圳湾公园": "assets/stamps/stamp-sz-504.webp",
  "莲花山公园": "assets/stamps/stamp-sz-505.webp",
  "梧桐山": "assets/stamps/stamp-sz-506.webp",
  "大鹏古城": "assets/stamps/stamp-sz-507.webp",
  "较场尾": "assets/stamps/stamp-sz-508.webp",
  "杨梅坑": "assets/stamps/stamp-sz-509.webp",
  "南澳西冲": "assets/stamps/stamp-sz-510.webp",
  "东西涌穿越": "assets/stamps/stamp-sz-511.webp",
  "官湖村": "assets/stamps/stamp-sz-512.webp",
  "甘坑客家小镇": "assets/stamps/stamp-sz-513.webp",
  "巽寮湾": "assets/stamps/stamp-sz-514.webp",
  "双月湾": "assets/stamps/stamp-sz-515.webp",
  "盐洲岛": "assets/stamps/stamp-sz-516.webp",
  "惠州西湖": "assets/stamps/stamp-sz-517.webp",
  "南昆山": "assets/stamps/stamp-sz-518.webp",
  "罗浮山": "assets/stamps/stamp-sz-519.webp",
  "东莞松山湖": "assets/stamps/stamp-sz-520.webp",
  "东莞可园": "assets/stamps/stamp-sz-521.webp",
  "珠海长隆海洋王国": "assets/stamps/stamp-sz-522.webp",
  "外伶仃岛": "assets/stamps/stamp-sz-523.webp",
  "东澳岛": "assets/stamps/stamp-sz-524.webp",
  "中山温泉": "assets/stamps/stamp-sz-525.webp",
  "佛山祖庙": "assets/stamps/stamp-sz-526.webp",
  "顺德美食之旅": "assets/stamps/stamp-sz-527.webp",
  "广州塔": "assets/stamps/stamp-sz-528.webp",
  "沙面岛": "assets/stamps/stamp-sz-529.webp",
  "长隆野生动物世界": "assets/stamps/stamp-sz-530.webp",
  "白云山": "assets/stamps/stamp-sz-531.webp",
  "阳江海陵岛": "assets/stamps/stamp-sz-532.webp",
  "汕头南澳岛": "assets/stamps/stamp-sz-533.webp",
  "潮州古城": "assets/stamps/stamp-sz-534.webp",
  "汕尾红海湾": "assets/stamps/stamp-sz-535.webp",
  "清远漂流": "assets/stamps/stamp-sz-536.webp",
  "韶关丹霞山": "assets/stamps/stamp-sz-537.webp",
  "梅州客家围龙屋": "assets/stamps/stamp-sz-538.webp",
  "湛江": "assets/stamps/stamp-sz-539.webp",
  "北海涠洲岛": "assets/stamps/stamp-sz-540.webp",
  "桂林阳朔": "assets/stamps/stamp-sz-541.webp",
  "厦门鼓浪屿": "assets/stamps/stamp-sz-542.webp",
  "肇庆七星岩": "assets/stamps/stamp-sz-543.webp",
  "江门开平碉楼": "assets/stamps/stamp-sz-544.webp",
  "茂名放鸡岛": "assets/stamps/stamp-sz-545.webp",
  "河源万绿湖": "assets/stamps/stamp-sz-546.webp",
  "从化温泉": "assets/stamps/stamp-sz-547.webp",
  "增城白水寨": "assets/stamps/stamp-sz-548.webp",
  "仙湖植物园": "assets/stamps/stamp-sz-550.webp",
  "锦绣中华": "assets/stamps/stamp-sz-551.webp",
  "海上世界": "assets/stamps/stamp-sz-552.webp",
  "深圳博物馆": "assets/stamps/stamp-sz-553.webp",
  "大芬油画村": "assets/stamps/stamp-sz-554.webp",
  "华侨城创意园": "assets/stamps/stamp-sz-555.webp",
  "深圳图书馆": "assets/stamps/stamp-sz-556.webp",
  "南头古城": "assets/stamps/stamp-sz-557.webp",
  "盐田海滨栈道": "assets/stamps/stamp-sz-558.webp",
  "深圳中心公园": "assets/stamps/stamp-sz-559.webp",
  "洪湖公园": "assets/stamps/stamp-sz-560.webp",
  "笔架山公园": "assets/stamps/stamp-sz-561.webp",
  "红树林海滨公园": "assets/stamps/stamp-sz-562.webp",
  "惠州双月湾观景台": "assets/stamps/stamp-sz-563.webp",
  "惠东平海古城": "assets/stamps/stamp-sz-564.webp",
  "博罗五矿温泉": "assets/stamps/stamp-sz-565.webp",
  "河源客天下": "assets/stamps/stamp-sz-566.webp",
  "东莞虎门大桥": "assets/stamps/stamp-sz-567.webp",
  "东莞观音山": "assets/stamps/stamp-sz-568.webp",
  "中山詹园": "assets/stamps/stamp-sz-569.webp",
  "珠海情侣路": "assets/stamps/stamp-sz-570.webp",
  "珠海圆明新园": "assets/stamps/stamp-sz-571.webp",
  "广州陈家祠": "assets/stamps/stamp-sz-572.webp",
  "广州北京路": "assets/stamps/stamp-sz-573.webp",
  "广州珠江夜游": "assets/stamps/stamp-sz-574.webp",
  "佛山南风古灶": "assets/stamps/stamp-sz-575.webp",
  "佛山千灯湖": "assets/stamps/stamp-sz-576.webp",
  "潮汕美食之旅": "assets/stamps/stamp-sz-577.webp",
  "汕头小公园": "assets/stamps/stamp-sz-578.webp",
  "揭阳黄满寨瀑布": "assets/stamps/stamp-sz-579.webp",
  "河源龙川霍山": "assets/stamps/stamp-sz-580.webp",
  "梅州雁南飞": "assets/stamps/stamp-sz-581.webp",
  "梅州灵光寺": "assets/stamps/stamp-sz-582.webp",
  "肇庆鼎湖山": "assets/stamps/stamp-sz-583.webp",
  "云浮新兴六祖故里": "assets/stamps/stamp-sz-584.webp",
  "阳春凌霄岩": "assets/stamps/stamp-sz-585.webp",
  "茂名浮山岭": "assets/stamps/stamp-sz-586.webp",
  "湛江特呈岛": "assets/stamps/stamp-sz-587.webp",
  "湛江硇洲岛": "assets/stamps/stamp-sz-588.webp",
  "清远英西峰林": "assets/stamps/stamp-sz-589.webp",
  "清远连州地下河": "assets/stamps/stamp-sz-590.webp",
  "韶关南华寺": "assets/stamps/stamp-sz-591.webp",
  "韶关乳源大峡谷": "assets/stamps/stamp-sz-592.webp",
  "河源九龙湾": "assets/stamps/stamp-sz-593.webp",
  "梅州大埔花萼楼": "assets/stamps/stamp-sz-594.webp",
  "南宁青秀山": "assets/stamps/stamp-sz-595.webp",
  "贺州黄姚古镇": "assets/stamps/stamp-sz-596.webp",
  "梧州骑楼城": "assets/stamps/stamp-sz-597.webp",
  "漳州土楼": "assets/stamps/stamp-sz-598.webp",
  "龙岩永定土楼": "assets/stamps/stamp-sz-599.webp",
  "泉州开元寺": "assets/stamps/stamp-sz-600.webp",
  "长沙岳麓山": "assets/stamps/stamp-sz-601.webp",
  "深圳光明小镇": "assets/stamps/stamp-sz-602.webp",
  "深圳东门老街": "assets/stamps/stamp-sz-603.webp",
  "深圳前海石公园": "assets/stamps/stamp-sz-604.webp",
  "汕头老妈宫戏台": "assets/stamps/stamp-sz-605.webp",
  "汕头陈慈黉故居": "assets/stamps/stamp-sz-606.webp",
  "潮州广济桥": "assets/stamps/stamp-sz-607.webp",
  "潮州开元寺": "assets/stamps/stamp-sz-608.webp",
  "潮州牌坊街美食": "assets/stamps/stamp-sz-609.webp",
  "揭阳进贤门": "assets/stamps/stamp-sz-610.webp",
  "汕尾凤山祖庙": "assets/stamps/stamp-sz-611.webp",
  "潮州凤凰山茶区": "assets/stamps/stamp-sz-612.webp",
  "南澳岛青澳湾": "assets/stamps/stamp-sz-613.webp",
  "汕头礐石风景区": "assets/stamps/stamp-sz-614.webp",
  "潮州韩文公祠": "assets/stamps/stamp-sz-615.webp",
  "潮汕工夫茶体验": "assets/stamps/stamp-sz-616.webp",
  "揭阳惠来海角甘泉": "assets/stamps/stamp-sz-617.webp",
  "汕头达濠鱼丸一条街": "assets/stamps/stamp-sz-618.webp",
  "南澳岛总兵府": "assets/stamps/stamp-sz-619.webp",
  "广州越秀公园五羊雕塑": "assets/stamps/stamp-sz-620.webp",
  "广州荔枝湾涌": "assets/stamps/stamp-sz-621.webp",
  "广州太古仓": "assets/stamps/stamp-sz-622.webp",
  "广州永庆坊": "assets/stamps/stamp-sz-623.webp",
  "广州红砖厂创意园": "assets/stamps/stamp-sz-624.webp",
  "广州海珠湿地": "assets/stamps/stamp-sz-625.webp",
  "广州黄埔古港": "assets/stamps/stamp-sz-626.webp",
  "广州从化石门森林公园": "assets/stamps/stamp-sz-627.webp",
  "广州花都圆玄道观": "assets/stamps/stamp-sz-628.webp",
  "广州番禺宝墨园": "assets/stamps/stamp-sz-629.webp",
  "广州增城派潭温泉": "assets/stamps/stamp-sz-630.webp",
  "广州南沙湿地": "assets/stamps/stamp-sz-631.webp",
  "花都芙蓉嶂": "assets/stamps/stamp-sz-632.webp",
  "从化流溪河森林公园": "assets/stamps/stamp-sz-633.webp",
  "增城挂绿荔枝广场": "assets/stamps/stamp-sz-634.webp",
  "顺德清晖园": "assets/stamps/stamp-sz-635.webp",
  "顺德均安蒸猪": "assets/stamps/stamp-sz-636.webp",
  "顺德伦教糕老字号": "assets/stamps/stamp-sz-637.webp",
  "顺德陈村花卉世界": "assets/stamps/stamp-sz-638.webp",
  "佛山梁园": "assets/stamps/stamp-sz-639.webp",
  "佛山岭南天地": "assets/stamps/stamp-sz-640.webp",
  "佛山三水荷花世界": "assets/stamps/stamp-sz-641.webp",
  "南海西樵山": "assets/stamps/stamp-sz-642.webp",
  "南海影视城": "assets/stamps/stamp-sz-643.webp",
  "佛山高明盈香生态园": "assets/stamps/stamp-sz-644.webp",
  "东莞华阳湖": "assets/stamps/stamp-sz-645.webp",
  "惠州双月湾黑排角": "assets/stamps/stamp-sz-646.webp",
  "珠海横琴长隆国际马戏城": "assets/stamps/stamp-sz-647.webp",
  "中山故居纪念馆": "assets/stamps/stamp-sz-648.webp",
  "江门新会小鸟天堂": "assets/stamps/stamp-sz-649.webp",
  "江门台山上下川岛": "assets/stamps/stamp-sz-650.webp",
  "云浮蟠龙洞": "assets/stamps/stamp-sz-651.webp",
  "肇庆砚洲岛": "assets/stamps/stamp-sz-652.webp",
  "清远千年瑶寨": "assets/stamps/stamp-sz-653.webp",
  "韶关南岭国家森林公园": "assets/stamps/stamp-sz-654.webp",
  "河源御临门温泉": "assets/stamps/stamp-sz-655.webp",
  "梅州叶剑英故居": "assets/stamps/stamp-sz-656.webp",
  "阳江阳春春湾石林": "assets/stamps/stamp-sz-657.webp",
  "茂名信宜大仁山": "assets/stamps/stamp-sz-658.webp",
  "湛江金沙湾": "assets/stamps/stamp-sz-659.webp",
  "刘公岛": "assets/stamps/stamp-wh-700.webp",
  "威海国际海水浴场": "assets/stamps/stamp-wh-701.webp",
  "环翠楼": "assets/stamps/stamp-wh-702.webp",
  "那香海": "assets/stamps/stamp-wh-703.webp",
  "韩乐坊": "assets/stamps/stamp-wh-704.webp",
  "海源公园": "assets/stamps/stamp-wh-705.webp",
  "猫头山": "assets/stamps/stamp-wh-706.webp",
  "火炬八街": "assets/stamps/stamp-wh-707.webp",
  "半月湾": "assets/stamps/stamp-wh-708.webp",
  "悦海公园": "assets/stamps/stamp-wh-709.webp",
  "威海公园": "assets/stamps/stamp-wh-710.webp",
  "金海滩": "assets/stamps/stamp-wh-711.webp",
  "成山头": "assets/stamps/stamp-wh-712.webp",
  "西霞口神雕山野生动物园": "assets/stamps/stamp-wh-713.webp",
  "海驴岛": "assets/stamps/stamp-wh-714.webp",
  "鸡鸣岛": "assets/stamps/stamp-wh-715.webp",
  "天鹅湖": "assets/stamps/stamp-wh-716.webp",
  "石岛赤山": "assets/stamps/stamp-wh-717.webp",
  "荣成博物馆": "assets/stamps/stamp-wh-718.webp",
  "文登天沐温泉": "assets/stamps/stamp-wh-719.webp",
  "乳山银滩": "assets/stamps/stamp-wh-720.webp",
  "大乳山": "assets/stamps/stamp-wh-721.webp",
  "圣水观": "assets/stamps/stamp-wh-722.webp",
  "蓬莱阁": "assets/stamps/stamp-wh-723.webp",
  "长岛": "assets/stamps/stamp-wh-724.webp",
  "烟台山": "assets/stamps/stamp-wh-725.webp",
  "养马岛": "assets/stamps/stamp-wh-726.webp",
  "张裕酒文化博物馆": "assets/stamps/stamp-wh-727.webp",
  "栈桥": "assets/stamps/stamp-wh-728.webp",
  "崂山": "assets/stamps/stamp-wh-729.webp",
  "八大关": "assets/stamps/stamp-wh-730.webp",
  "金沙滩": "assets/stamps/stamp-wh-731.webp",
  "曲阜三孔": "assets/stamps/stamp-wh-733.webp",
  "济南趵突泉": "assets/stamps/stamp-wh-734.webp",
};

// Check if destination has an AI-generated stamp image
function hasStampImage(dest) {
  return !!STAMP_IMAGES[dest.name];
}

function getStampImagePath(dest) {
  return STAMP_IMAGES[dest.name] || null;
}

// ========== SVG Fallback System ==========

const STAMP_PALETTES = [
  { main: '#8B4513' },
  { main: '#C62828' },
  { main: '#AD1457' },
  { main: '#6A1B9A' },
  { main: '#283593' },
  { main: '#0277BD' },
  { main: '#00695C' },
  { main: '#2E7D32' },
  { main: '#F57F17' },
  { main: '#BF360C' },
  { main: '#4E342E' },
  { main: '#37474F' },
];

function getDestIcon(dest) {
  var name = dest.name;
  if (name.indexOf('长城') >= 0 || name.indexOf('慕田峪') >= 0 || name.indexOf('居庸关') >= 0 || name.indexOf('箭扣') >= 0 || name.indexOf('司马台') >= 0) return '\u{1F3EF}';
  if (name.indexOf('滑雪') >= 0 || name.indexOf('雪场') >= 0) return '\u26F7';
  if (name.indexOf('温泉') >= 0) return '\u2668';
  if (name.indexOf('水库') >= 0 || name.indexOf('湖') >= 0) return '\u{1F3DE}';
  if (name.indexOf('峡') >= 0 || name.indexOf('谷') >= 0) return '\u{1F3D4}';
  if (name.indexOf('山') >= 0 || name.indexOf('岭') >= 0 || name.indexOf('峰') >= 0) return '\u26F0';
  if (name.indexOf('寺') >= 0 || name.indexOf('庙') >= 0 || name.indexOf('陵') >= 0) return '\u{1F6D5}';
  if (name.indexOf('村') >= 0 || name.indexOf('镇') >= 0 || name.indexOf('古') >= 0) return '\u{1F3D8}';
  if (name.indexOf('公园') >= 0 || name.indexOf('森林') >= 0) return '\u{1F333}';
  if (name.indexOf('动物') >= 0 || name.indexOf('野生') >= 0) return '\u{1F43E}';
  if (name.indexOf('湿地') >= 0 || name.indexOf('鸭') >= 0) return '\u{1F986}';
  if (name.indexOf('花') >= 0 || name.indexOf('桃') >= 0) return '\u{1F338}';
  if (name.indexOf('艺术') >= 0 || name.indexOf('798') >= 0) return '\u{1F3A8}';
  if (name.indexOf('草原') >= 0 || name.indexOf('坝上') >= 0) return '\u{1F40E}';
  if (name.indexOf('海') >= 0 || name.indexOf('河') >= 0) return '\u{1F30A}';
  if (name.indexOf('街') >= 0 || name.indexOf('巷') >= 0) return '\u{1F3EE}';
  if (name.indexOf('酒') >= 0 || name.indexOf('葡萄') >= 0) return '\u{1F377}';
  if (name.indexOf('冰') >= 0 || name.indexOf('雪') >= 0) return '\u2744';
  var themes = dest.themes || [];
  if (themes.indexOf('露营') >= 0) return '\u26FA';
  if (themes.indexOf('美食') >= 0) return '\u{1F35C}';
  if (themes.indexOf('赏花') >= 0) return '\u{1F338}';
  if (themes.indexOf('历史') >= 0) return '\u{1F4DC}';
  if (themes.indexOf('爬山') >= 0) return '\u26F0';
  return '\u{1F4CD}';
}

function getStampDesign(dest) {
  var id = dest.id;
  var palette = STAMP_PALETTES[id % STAMP_PALETTES.length];
  var icon = getDestIcon(dest);
  var rotation = ((id * 17 + 7) % 30) - 15;
  return { palette: palette, icon: icon, rotation: rotation, name: dest.name.slice(0, 6) };
}

function _svgShape(size, stroke, type) {
  var c = size / 2, r = size / 2 - 4;
  switch (type) {
    case 0: return '<circle cx="' + c + '" cy="' + c + '" r="' + r + '" fill="none" stroke="' + stroke + '" stroke-width="3" stroke-dasharray="6 3"/>';
    case 1: return '<circle cx="' + c + '" cy="' + c + '" r="' + r + '" fill="none" stroke="' + stroke + '" stroke-width="2.5"/><circle cx="' + c + '" cy="' + c + '" r="' + (r - 5) + '" fill="none" stroke="' + stroke + '" stroke-width="1.5"/>';
    case 2: {
      var pts = [];
      for (var i = 0; i < 8; i++) { var a = Math.PI / 8 + i * Math.PI / 4; pts.push((c + r * Math.cos(a)) + ',' + (c + r * Math.sin(a))); }
      return '<polygon points="' + pts.join(' ') + '" fill="none" stroke="' + stroke + '" stroke-width="2.5"/>';
    }
    case 3: return '<rect x="4" y="4" width="' + (size - 8) + '" height="' + (size - 8) + '" rx="12" fill="none" stroke="' + stroke + '" stroke-width="2.5"/>';
    case 4: {
      var pts2 = [];
      for (var j = 0; j < 6; j++) { var a2 = -Math.PI / 2 + j * Math.PI / 3; pts2.push((c + r * Math.cos(a2)) + ',' + (c + r * Math.sin(a2))); }
      return '<polygon points="' + pts2.join(' ') + '" fill="none" stroke="' + stroke + '" stroke-width="2.5"/>';
    }
    default: return '<circle cx="' + c + '" cy="' + c + '" r="' + r + '" fill="none" stroke="' + stroke + '" stroke-width="3" stroke-dasharray="6 3"/>';
  }
}

function generateStampSVG(dest, size) {
  size = size || 64;
  var design = getStampDesign(dest);
  var stroke = design.palette.main;
  var shapeType = dest.id % 5;
  var shapeEl = _svgShape(size, stroke, shapeType);
  var cx = size / 2;
  var displayName = design.name.length > 4 ? design.name.slice(0, 4) : design.name;
  var fontSize = displayName.length > 3 ? 7 : 8;

  return '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ' + size + ' ' + size + '">' +
    shapeEl +
    '<text x="' + cx + '" y="' + (size * 0.28) + '" text-anchor="middle" font-size="6" font-weight="bold" fill="' + stroke + '" font-family="PingFang SC,sans-serif">\u5DF2\u6253\u5361</text>' +
    '<text x="' + cx + '" y="' + (size * 0.52) + '" text-anchor="middle" font-size="16">' + design.icon + '</text>' +
    '<text x="' + cx + '" y="' + (size * 0.76) + '" text-anchor="middle" font-size="' + fontSize + '" font-weight="bold" fill="' + stroke + '" font-family="PingFang SC,sans-serif">' + displayName + '</text>' +
    '</svg>';
}

function getStampDataURL(dest) {
  if (hasStampImage(dest)) return getStampImagePath(dest);
  return 'data:image/svg+xml,' + encodeURIComponent(generateStampSVG(dest, 64));
}

function generateLargeStampHTML(dest) {
  if (hasStampImage(dest)) {
    var design = getStampDesign(dest);
    return '<img src="' + getStampImagePath(dest) + '" alt="' + dest.name + ' stamp" style="width:280px;height:auto;transform:rotate(' + design.rotation + 'deg);border-radius:8px;">';
  }

  var d = getStampDesign(dest);
  var stroke = d.palette.main;
  var size = 200;
  var shapeType = dest.id % 5;
  var shapeEl = _svgShape(size, stroke, shapeType);
  var cx = size / 2;
  var displayName = d.name;
  var fontSize = displayName.length > 4 ? 16 : 20;
  var dateStr = new Date().toLocaleDateString('zh-CN', { month: 'short', day: 'numeric' });

  return '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ' + size + ' ' + size + '" style="width:200px;height:200px;transform:rotate(' + d.rotation + 'deg)">' +
    shapeEl +
    '<text x="' + cx + '" y="' + (size * 0.22) + '" text-anchor="middle" font-size="14" font-weight="800" fill="' + stroke + '" font-family="PingFang SC,sans-serif" letter-spacing="4">\u2605 \u5DF2\u6253\u5361 \u2605</text>' +
    '<text x="' + cx + '" y="' + (size * 0.48) + '" text-anchor="middle" font-size="32">' + d.icon + '</text>' +
    '<text x="' + cx + '" y="' + (size * 0.68) + '" text-anchor="middle" font-size="' + fontSize + '" font-weight="800" fill="' + stroke + '" font-family="PingFang SC,sans-serif">' + displayName + '</text>' +
    '<text x="' + cx + '" y="' + (size * 0.82) + '" text-anchor="middle" font-size="11" fill="' + stroke + '" font-family="PingFang SC,sans-serif" opacity="0.6">' + dateStr + '</text>' +
    '</svg>';
}
